### ISSUE TITLE
Community Communication and Engagement Q1

### ISSUE THREAD

**Issue by dhuseby** [libp2p/libp2p#149]
```[tasklist]
### Meetings
- [ ] https://github.com/libp2p/libp2p/issues/150
- [ ] https://github.com/libp2p/libp2p/issues/151
- [ ] https://github.com/libp2p/libp2p/issues/152
- [ ] https://github.com/libp2p/libp2p/issues/153
- [ ] https://github.com/libp2p/libp2p/issues/154
- [ ] https://github.com/libp2p/libp2p/issues/155
```
```[tasklist]
### Website Improvements
- [ ] https://github.com/libp2p/libp2p/issues/162
- [ ] https://github.com/libp2p/libp2p/issues/163
- [ ] https://github.com/libp2p/libp2p/issues/164
- [ ] https://github.com/libp2p/libp2p/issues/165
- [ ] https://github.com/libp2p/libp2p/issues/166
- [ ] https://github.com/libp2p/libp2p/issues/167
```

```[tasklist]
### Maintainership
- [ ] https://github.com/libp2p/libp2p/issues/226
```

**Comment by dhuseby** [comment]
Original tracking doc: https://docs.google.com/document/d/1CwXcP0O3EOZAZ-nIFygoJA3ihqYIE45k/edit?usp=sharing&ouid=111218818098536518346&rtpof=true&sd=true

**Comment by dhuseby** [comment]
Completed
