### ISSUE TITLE
Optimize Community Infrastructure

### ISSUE THREAD

**Issue by dhuseby** [libp2p/libp2p#204]
```[tasklist]
### Chores
- [ ] https://github.com/libp2p/libp2p/issues/156
- [ ] https://github.com/libp2p/libp2p/issues/157
- [ ] https://github.com/libp2p/libp2p/issues/158
- [ ] https://github.com/libp2p/libp2p/issues/159
- [ ] https://github.com/libp2p/libp2p/issues/160
- [ ] https://github.com/libp2p/libp2p/issues/161
```
