### ISSUE TITLE
QUIC Transport

### ISSUE THREAD

**Issue by bigs** [libp2p/libp2p#35]
Meta-issue to track the progress of getting the QUIC transport published for go-libp2p. Some notes per Marten and my conversation this evening:

### Testing Concerns

- Is there an IPFS test network we could test the transport on at scale?
  - Ideally with telemetry collection so we'd not want actual users onboard
  - Infra team?
- What's the current state of telemetry in IPFS/libp2p?
  - Tracing ETA?
  - Data collection & processing

### TODOS

- [ ] Get as many crypto-savvy reviewers to go over [the latest refactor of the QUIC transport](https://github.com/marten-seemann/libp2p-quic-transport/tree/feat/refactor)
- [x] Bring `libp2p-quic-transport` into the `libp2p` org as `go-libp2p-quic-transport`
- [ ] Determine a set of metrics to evaluate the success of QUIC
  - Dial speed
  - Total round trips in negotiating upgrades

Most of the heavy lifting is done and it would be great to have a demo-able version ready by the July meetings in Berlin.

**Comment by bigs** [comment]
@mgoelzer @marten-seemann

**Comment by ghost** [comment]
whats happening in July ? I live in Berlin and use QUIC, Flatbuffers and GRPC, so its interesting for me.

**Comment by ghost** [comment]
getting QUIC into lip2p would be highly useful.

**Comment by bigs** [comment]
@gedw99 I'm not sure if applications are still open but the information [can be found here!](https://github.com/ipfs/developer-meetings). Would love to see you there!

**Comment by whyrusleeping** [comment]
one major metric i want to see is dial speed. 

We have a pretty significant amount of data on dial speed across the network using existing transports here: https://github.com/libp2p/go-libp2p-swarm/pull/57#issuecomment-385982050

its around 1-2s for the most part, not infrequently 3 or more seconds though. If quic can drop that down noticeably, i'd say its a success.

**Comment by marten-seemann** [comment]
I just outlined the design rationale for the handshake in https://github.com/marten-seemann/libp2p-quic-transport/issues/3. Please note that the code is not yet merged into the master branch, please have a look at the feat/refactor branch.

**Comment by whyrusleeping** [comment]
@marten-seemann oh btw! In case you hadn't noticed, the transport refactor has merged, all the way up into go-ipfs! I think we're ready to start testing out QUIC in the main codebase :)

**Comment by ghost** [comment]
@bigs thanks. I live in Berlin and so applied for the meeting.  Do you have access to the form submissions. I used my github handle here in the application.
Me and my team are building a few experimental things on top of IPFS with CRDT, CQRS style architectures. I participate in the large DIN meeting in Germany also and many of the large projects in Germany are talking about using P2p and CRDT to solve some data silo and collaboration problems. The ground is shifting :)

**Comment by ghost** [comment]
@whyrusleeping I cant see it in go-ipfs.
which branch of go-ipfs ? Would like to start working of it and trying a few use cases out.

**Comment by whyrusleeping** [comment]
@gedw99 current master, fc05376, is where the refactor landed.

**Comment by marten-seemann** [comment]
Hi guys, I just renamed the repo to go-libp2p-quic-transport and tried to transfer it to github.com/libp2p, but apparently I don't have the necessary permissions to create repositories there (I'm not even a member of that organization. Can anyone invite me there?).

**Comment by ghost** [comment]
@whyrusleeping Can you add @marten-seemann (I'm not an owner) or bounce this to someone else?

**Comment by whyrusleeping** [comment]
Hey @marten-seemann, sorry about that! sent you an invite :)

**Comment by bigs** [comment]
@marten-seemann What's the current status for this? Can I help you get some reviewers? Have you opened a PR for your changes on the transport repo?

**Comment by Stebalien** [comment]
The libp2p transport part is here: https://github.com/libp2p/go-libp2p-quic-transport

**Comment by marten-seemann** [comment]
@bigs: This should be ready for experiments now (as soon as I create a new QUIC version for these experiments, https://github.com/libp2p/go-libp2p-quic-transport/issues/11). Getting some reviews before that would be awesome.

I don't need any changes in the transport repo. Please have a look at my modified *libp2p echo* example over QUIC: https://github.com/marten-seemann/go-libp2p/commit/044a9b45e8c1f61f04207f429af70cf4b7a3abc1.

**Comment by whyrusleeping** [comment]
It would be really nice to have a 'libp2p transport plugin' in go-ipfs.  That way we could easily plug in experimental QUIC things to test them out, and also easily plug in the Tor transport we've been toying with.

**Comment by bigs** [comment]
OK, lovely! I think that’s a good test vector, @whyrusleeping. Ideally something you can opt into for users. We should make an issue for that and consider it the final criteria for this issue.

**Comment by marten-seemann** [comment]
Closing since we've had a QUIC transport in go-libp2p for the longest time.
