### ISSUE TITLE
Proposal:  libp2p OKRs + Roadmap for this Year

### ISSUE THREAD

**Issue by ghost** [libp2p/libp2p#38]
The doc below has proposed OKRs and a features roadmap (second tab) for the libp2p in 2018 through mid-2019.   It is a WIP.

https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=0

To get to completion, we'll need to:

- [ ] Have some discussion in this issue to agree about goals and dates
- [ ] Make all the KRs quantifiable (eg, add a ship date for binary or event KRs)
- [ ] Break off a subset of KRs for Q3 beginning Jul 2018
- [ ] Distinguish between committed vs aspirational OKRs?
- [ ] Add dates to roadmap

@whyrusleeping @diasdavid @bigs @Stebalien

**Comment by raulk** [comment]
This is outdated now.
