### ISSUE TITLE
Docs:  Create an issue for each libp2p Berlin poster -> docs task

### ISSUE THREAD

**Issue by ghost** [libp2p/libp2p#40]
This is a meta issue.  It describes a set of issues that need to be created.

All of the posters from Berlin are here:
https://drive.google.com/drive/u/0/folders/1te63vJYCmm7jito2c8-N4PYKWUYDf9Bq

For each one that is relevant to libp2p, we should create an issue linking to it and requesting that someone create a docs PR covering the topic in writing.

(Per discussion with @Mr0grog in Berlin.)

**Comment by Mr0grog** [comment]
For the IPFS ones, I’m going to add the issues to https://github.com/ipfs/docs and recommend writing docs in the [`concepts` directory](https://github.com/ipfs/docs/tree/master/content/guides/concepts); what’s the most relevant place here for Libp2p ones? https://github.com/libp2p/docs doesn’t really seem to have a place for them (or anything), but is that still where these belong?

**Comment by ghost** [comment]
@Mr0grog I think we should start a concepts section for libp2p.  My gut feeling is we should put the content in https://github.com/libp2p/specs.  That entire repo will probably get restructured at some point.  However, there is a case to made that implementation details like those posters do not belong in the specs repo.  https://github.com/libp2p/docs looks like a greenfield site to me, so we could do pretty much anything we want in there.

Sorry for the ambiguous answer.  The long term solution is to sit down and figure out what we want the overall libp2p docs experience to be like, and then move content around and edit stuff to achieve that.

**Comment by Mr0grog** [comment]
> My gut feeling is we should put the content in https://github.com/libp2p/specs …however, there is a case to made that implementation details like those posters do not belong in the specs repo.

OK, how about one of these two:

1. Add an `concepts` directory (to clearly differentiate from specs and spec-style content) to https://github.com/libp2p/specs and add the issues to that repo. Issues will suggest writing a doc in the `concepts` directory.

2. Add a `concepts` directory to https://github.com/libp2p/docs and add the issues to that repo. Issues will suggest writing a doc in the `concepts` directory.

I’d lean towards (2), since it sounds like this is about content that will eventually be destined for the docs site anyway. It’s fine that it’ll move around, but at least it’ll be in the right repo to start with. (The main counter-argument I can think of is that this stuff won’t be as discoverable right now.)

**Comment by Mr0grog** [comment]
I added the ones that I thought were IPFS-specific to the IPFS docs repo. I think these ones are more Libp2p-focused, but let me know if you think some should be lifted up to IPFS:

- [x] DHT (Kademlia) (libp2p/docs#3)
- [x] Floodsub (libp2p/docs#4)
- [x] IPRS (I put IPNS with IPFS, but I’m thinking this more generalized version belongs with Libp2p. Not totally sure.) (libp2p/docs#5)
- [x] Rendezvous (libp2p/docs#6)
- [x] Routing (libp2p/docs#7)
- [x] SecIO (libp2p/docs#8)

**Comment by lanzafame** [comment]
I would suggest going with @Mr0grog's option 2 as there is a significant benefit to keeping a similar structure to the ipfs/docs, which is that a lot of developers that come to libp2p are going to go looking for existing examples of how things are implemented using libp2p, which ipfs is a prime example but also the opposite is true for devs playing around with ipfs and then wanting to dig into the networking stack. I think this would help reduce overhead, similar to the standard readme format.

**Comment by ghost** [comment]
Yes, thumbs up on option 2 and retaining a parallel structure to IPFS.

Also:
>IPRS (I put IPNS with IPFS, but I’m thinking this more generalized version belongs with Libp2p. Not totally sure.)

I think it's probably the right choice for IPNS, yes.  From an engineering standpoint, IPNS is a very thin wrapper around the DHT, which is libp2p.  But from a user perspective, it's exposed as an IPFS concept so it makes sense in ipfs/docs.

**Comment by Mr0grog** [comment]
I’ve created issues for all of these and linked them in https://github.com/libp2p/libp2p/issues/40#issuecomment-407920002. The [libp2p/docs](https://github.com/libp2p/docs) repo now also has a `concepts` folder with a readme that explains what they should cover.

Closing this issue as completed.
