### ISSUE TITLE
Roadmap: Rendezvous Protocol

### ISSUE THREAD

**Issue by jacobheun** [libp2p/libp2p#66]
# Rendezvous Protocol Roadmap
This roadmap aims to identify the requirements and plan for rolling out Rendezvous Services to the greater libp2p/ipfs network. This also aims to cover the decommissioning of the current \*-star rendezvous servers (websocket-star, webrtc-star, etc), as they will be replaced with new Libp2p servers running the Rendezvous Protocol

**Note**: Dates listed are tentative unless otherwise specified.

* **July 1, 2019** [Decommission \*-star servers](#decommission-star-servers)

### Needs
- [X] **January** Finalize a draft iteration of the [rendezvous protocol spec](https://github.com/libp2p/specs/blob/e1083c1f9d8f7afc0d65a43a12b05492f3873385/rendezvous/README.md)
- **February** Implement the rendezvous protocol; **Revision: DRAFT; 2019-01-18**
  - [ ] Finish the [go implementation](https://github.com/libp2p/go-libp2p-rendezvous)
  - [ ] Finish the [js implementation](https://github.com/libp2p/js-libp2p-rendezvous)
    
- **March** Roll out rendezvous to ipfs
  - [ ] add to go-ipfs
  - [ ] add to js-ipfs  
  
- **April** Launch rendezvous servers
  - [ ] Add rendezvous protocol to libp2p daemon
  - [ ] Coordinate with infra to create deployment artifacts (scripts, etc)
  
- **April** Work with predetermined community members/dapps teams to pilot
  - [ ] Determine pilot members/apps
  - [ ] Assist with integrating rendezvous for pilots

- [ ] **May** Create migration path for developers from \*-star transports to rendezvous
- [ ] **May** Announce decommission date of \*-star servers and point to the migration paths
  - [ ] Add disclaimer to transport/server readme's
  - [ ] Twitter, reddit, irc, Discuss, ...?

- [ ] **July 1** Shutdown the \*-star servers :tada:
