### ISSUE TITLE
Revisit Milestone 2

### ISSUE THREAD

**Issue by daviddias** [libp2p/libp2p#7]
As @whyrusleeping brought up in the last Sprint call, we need to revisit libp2p milestone 2.

@whyrusleeping can you captain this? Ideas discussed:
- break MS2 into 3 separate milestones
- defer them to Q4

Let's not forget to update the waffle board.

**Comment by whyrusleeping** [comment]
Alright, so milestone 2 is currently:

> Summary: Improve the connectivity of go-libp2p. Have the technical discussions that will enable us to follow a plan to achieve a better connected graph.
- Tasks
  - [ ] Technical Discussion: Define a strategy for connection closing
    - https://github.com/libp2p/go-libp2p/issues/45
    - https://github.com/ipfs/go-ipfs/issues/3065
    - https://github.com/ipfs/notes/issues/110
  - [ ] Implement the strategy for connection closing in go-libp2p
  - [ ] Technical Discussion: Definte a strategy for Relay (or multiple Relay)
    - https://github.com/ipfs/notes/issues/110
  - [ ] Implement Relay in go-libp2p
  - [ ] Technical Discussion: Improve NAT Traversal
    - https://github.com/ipfs/notes/issues/110
    - https://github.com/ipfs/go-ipfs/issues/2509
  - [ ] Improve NAT traversal in go-libp2p

This is a very broad collection of things. We're not going to be able to achieve this in Q3.

Lets break this down and shuffle things around a bit.

The connection closing stuff belongs under the ['improve resource consumption'](https://github.com/ipfs/go-ipfs/milestone/5) milestone, but it might also want to be its own milestone. We still need to have that discussion, after the discussion we can break out more action items.

Relay should be its own milestone. 

Improve NAT Traversal also belongs in its own milestone, right now its not clear what is needed to accomplish that. (obviously things like relay and dialme will help, but are there others? how will we know when things work?)

**Comment by whyrusleeping** [comment]
Opened three milestones in go-libp2p: https://github.com/libp2p/go-libp2p/milestones

**Comment by daviddias** [comment]
👌🏽
